<?php
$insert_cinfo = "INSERT INTO `cinfo`(`sl`,
									 `invoice`,
									 `post_code`,
									 `name`,
									 `father`,
									 `mother`,
									 `dob`,
									 `age_as`,
									 `sex`,
									 `nid`,
									 `nid_no`,
									 `passport`,
									 `passport_no`,
									 `breg`,
									 `breg_no`,
									 `religion`,
									 `mstatus`,
									 `s_name`,
									 `ffq`,
									 `homedistrict`,
									 `present_care`,
									 `present_vill`,
									 `present_dist`,
									 `present_ps`,
									 `present_post`,
									 `present_pcode`,
									 `permanent_care`,
									 `permanent_vill`,
									 `permanent_dist`,
									 `permanent_ps`,
									 `permanent_post`,
									 `permanent_pcode`,
									 `mobile`,
									 `email`,
									 `ref_name_1`,
									 `ref_post_1`,
									 `ref_org_1`,
									 `ref_contact_1`,
									 `ref_mail_1`,
									 `ref_name_2`,
									 `ref_post_2`,
									 `ref_org_2`,
									 `ref_contact_2`,
									 `ref_mail_2`,
									 `departmental`,
									 `loginIP`,
									 `inTime`,
									 `extime`,
									 `vcode`)

									VALUES('0',
									'$ftcode',
									'$post_code',
									'$name',
									'$fathername',
									'$mothername',
									'$dob',
									'$age_as',
									'$sex',
									'$nid',
									'$nid_no',
									'$passport',
									'$passport_no',
									'$breg',
									'$breg_no',
									'$religion',
									'$mstatus',
									'$s_name',
									'$ffq',
									'$homedistrict',
									'$present_care',
									'$present_vill',
									'$present_dist',
									'$present_ps',
									'$present_post',
									'$present_pcode',
									'$permanent_care',
									'$permanent_vill',
									'$permanent_dist',
									'$permanent_ps',
									'$permanent_post',
									'$permanent_pcode',
									'$mobileno',
									'$email',
									'$ref_name_1',
									'$ref_post_1',
									'$ref_org_1',
									'$ref_contact_1',
									'$ref_mail_1',
									'$ref_name_2',
									'$ref_post_2',
									'$ref_org_2',
									'$ref_contact_2',
									'$ref_mail_2',
									'$dept',
									'$ip',
									'$applytime',
									'$extime',
									'$code')";

$insert_cedu = "
INSERT INTO `cedu` (`sl` ,
`s_exam` ,`s_roll` ,`s_board` ,`s_year` ,`s_group` ,`s_result` ,`s_result_type` ,`s_result_eq` ,
`h_exam` ,`h_roll` ,`h_board` ,`h_year` ,`h_group` ,`h_result` ,`h_result_type` ,`h_result_eq` ,
`g_exam` ,`g_sub` ,`g_institute` , `g_year` ,`g_duration` ,`g_result` ,`g_result_type` ,`g_result_eq` ,
`m_exam` ,`m_sub` ,`m_institute` , `m_year` ,`m_duration` ,`m_result` ,`m_result_type` ,`m_result_eq` ,
`job_exp` , `5year_exp`, `2year_exp`  ,`invoice`, `4year_exp` , `22year_exp` , `asso_mem` ,`dip_cer`,`trai6`) 
VALUES ('0',
'$exam1','$roll1','$institute1','$year1','$subject1','$result_gpa1','$result1','$result_eq1',
'$exam2','$roll2','$institute2','$year2','$subject2','$result_gpa2','$result2','$result_eq2',
'$exam3','$subject3','$institute3','$year3','$duration3','$result_gpa3','$result3','$result_eq3',
'$exam4','$subject4','$institute4','$year4','$duration4','$result_gpa4','$result4','$result_eq4',
'$job_exp','$progexp5','$progexp2','$photo','$progexp4','$progexp22', '$membercs', '$cerddc','training')";

?>

